### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by MulverineX** [DjDeveloperr/ytdl_core#1]
`main.ts`
```ts
import { getBasicInfo } from "https://deno.land/x/ytdl_core/mod.ts";

console.log(await getBasicInfo('TOgz_3q3uw0'))
```
```bash
$ deno run -A main.ts
error: Uncaught (in promise) TypeError: Cannot read property 'storyboards' of undefined
    info.player_response.storyboards &&
                         ^
    at Module.getStoryboards (https://deno.land/x/ytdl_core@0.0.1/src/info_extras.ts:323:26)
    at getBasicInfo (https://deno.land/x/ytdl_core@0.0.1/src/info.ts:85:25)
    at async file:///W:/workspace/web/refracture/backend/main.ts:3:13
```

**Comment by DjDeveloperr** [comment]
Fixed with v0.0.2
