### ISSUE TITLE
Cannot read property 'player_response' of undefined

### ISSUE THREAD

**Issue by 89z** [DjDeveloperr/ytdl_core#2]
Using this file:

~~~js
import ytdl from "https://deno.land/x/ytdl_core/mod.ts";
ytdl("vRXZj0DzXIA");
~~~

I get this result:

~~~
error: Uncaught (in promise) TypeError: Cannot read property 'player_response' of undefined
      if (newInfo.player_response) {
                  ^
    at pipeline (https://deno.land/x/ytdl_core@v0.0.2/src/info.ts:197:19)
    at async getBasicInfo (https://deno.land/x/ytdl_core@v0.0.2/src/info.ts:61:14)
    at async getInfo (https://deno.land/x/ytdl_core@v0.0.2/src/info.ts:444:14)
    at async ytdl (https://deno.land/x/ytdl_core@v0.0.2/src/video.ts:186:16)
~~~

**Comment by DjDeveloperr** [comment]
Can't reproduce 🤔 Perhaps you got rate limited? I think I forgot adding checks for rate limits.

**Comment by 89z** [comment]
No, thats not whats happening. Maybe you have a cURL command that does what this package does, I could test that?

**Comment by DjDeveloperr** [comment]
Mhm, can you try from main branch for once? I've added response status checks so that it gives proper error in case it's a bad status

**Comment by 89z** [comment]
How do I use the main branch, I am not too expert

**Comment by DjDeveloperr** [comment]
import from `https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/mod.ts`

**Comment by DjDeveloperr** [comment]
It's hard to debug this error since I can't reproduce. Can you run it again with --reload flag?

**Comment by 89z** [comment]
Cant you just add more error checking? Here is new error:

~~~
error: Uncaught (in promise) TypeError: Cannot read property 'player_response' of undefined
      info.player_response,
           ^
    at validate (https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/src/info.ts:46:12)
    at pipeline (https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/src/info.ts:209:11)
    at async getBasicInfo (https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/src/info.ts:62:14)
    at async getInfo (https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/src/info.ts:445:14)
    at async ytdl (https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/main/src/video.ts:188:16)
~~~

**Comment by DjDeveloperr** [comment]
I'm not sure about this error. Since this module is a port of [node-ytdl-core](https://github.com/fent/node-ytdl-core), could you perhaps try fetching the same video on that module? So that I know if it's an error introduced in the port.

**Comment by 89z** [comment]
Yeah, using the same video, this program works fine:

~~~js
const fs = require('fs');
const ytdl = require('ytdl-core');

ytdl('http://www.youtube.com/watch?v=vRXZj0DzXIA')
  .pipe(fs.createWriteStream('video.mp4'));
~~~

At first I thought it was broken too, as it was just hanging forever. But I realized they are defaulting to this stupid quality, so a 3 minute video is like 375 MB.

**Comment by DjDeveloperr** [comment]
Thanks! I'll try to track down this issue further.

**Comment by 89z** [comment]
closing this, because I dont care anymore
